app:
    resource: "@AppBundle/Controller/"
    type:     annotation

list:
    path:      /list
    defaults:  { _controller: AppBundle:Crawler:list }
search:
    path:      /search
    defaults:  { _controller: AppBundle:Crawler:search }
doCrawl:
    path:      /doCrawl
    defaults:  { _controller: AppBundle:Crawler:doCrawl }
crawlResults:
    path:      /crawl
    defaults:  { _controller: AppBundle:Crawler:crawl }
detail:
    path:      /detail
    defaults:  { _controller: AppBundle:Crawler:detail }