AppBundle\Entity\Job:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\JobRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: text
        company:
            type: text
        location:
            type: text
        description:
            type: text
    lifecycleCallbacks: {  }
